apiVersion: v1
kind: ConfigMap
metadata:
  name: foxlake-chart-kubeblocks-values
  labels:
    {{- include "kubeblocks.labels" . | nindent 4 }}
  {{- if .Values.keepAddons }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  values-kubeblocks-override.yaml: |-
    {{- get ( .Values | toYaml | fromYaml ) "foxlake" | toYaml | nindent 4 }}