apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: foxlake-s3-secret
stringData:
{{- if .Values.s3.accessKey }}
  s3AccessKey: {{ .Values.s3.accessKey }}
{{- end }}
{{- if .Values.s3.secretKey }}
  s3SecretKey: {{ .Values.s3.secretKey }}
{{- end }}
{{- if .Values.minio.accessKey }}
  minioAccessKey: {{ .Values.minio.accessKey }}
{{- end }}
{{- if .Values.minio.secretKey }}
  minioSecretKey: {{ .Values.minio.secretKey }}
{{- end }}