# Default values for foxlake.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


clusterVersionOverride: ""

# for foxlake
image:
  repository: apecloud/foxlake
  pullPolicy: Always
  tag: "main"

# for foxlake-metadb
mysql:
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "latest"

minio:
  bucketName: "foxlake"
  rootUser: "foxlake"