apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "clustername" . }}
  labels: {{ include "apecloud-mysql-cluster.labels" . | nindent 4 }}
spec:
  {{- if and (eq .Values.mode "raftGroup") .Values.proxyEnabled }}
  clusterDefinitionRef: apecloud-mysql-scale  # ref clusterdefinition.name
  {{- else }}
  clusterDefinitionRef: apecloud-mysql        # ref clusterdefinition.name
  {{- end }}
  clusterVersionRef: {{ .Values.version }}
  terminationPolicy: {{ .Values.terminationPolicy }}
  affinity:
    {{- with .Values.topologyKeys }}
    topologyKeys: {{ . | toYaml | nindent 6 }}
    {{- end }}
  {{- with $.Values.tolerations }}
  tolerations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  componentSpecs:
    - name: mysql
      componentDefRef: mysql # ref clusterdefinition componentDefs.name
      monitor: {{ .Values.monitor | default false }}
      replicas: {{ .Values.replicas | default 3 }}
      enabledLogs:
        - slow
        - error
      serviceAccountName: {{ include "apecloud-mysql-cluster.serviceAccountName" . }}
      resources:
        limits:
          cpu: {{ .Values.cpu | quote }}
          memory: {{ .Values.memory | quote }}
        requests:
          cpu: {{ .Values.cpu | quote }}
          memory: {{ .Values.memory | quote }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.storageSize }}
    {{ if and (eq .Values.mode "raftGroup") .Values.proxyEnabled }}
    {{- template "apecloud-mysql-cluster.proxyComponents" }}
    {{ end}}